# Generated by Django 6.0.4 on 2026-04-18 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "student_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "Öğrenci"), ("guest", "Misafir")],
                        default="guest",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.userprofile",
            ),
        ),
    ]
