# Generated by Django 4.2.11 on 2026-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_options_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
