# Generated by Django 4.2.11 on 2026-05-11 13:14

from django.db import migrations, models
import django.db.models.deletion
from pgvector.django import VectorExtension
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_course_semester'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='chat.universitycontent')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name'], name='chat_conten_model_n_20d6a1_idx'), models.Index(fields=['text_hash'], name='chat_conten_text_ha_d37d40_idx')],
            },
        ),
    ]
